// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQ8OHaAlA7-xa4GB5efI9ppsppR2eVwh0',
    appId: '1:429125840929:web:abbf9a2ee001abc4037360',
    messagingSenderId: '429125840929',
    projectId: 'chikitsha-munshi',
    authDomain: 'chikitsha-munshi.firebaseapp.com',
    storageBucket: 'chikitsha-munshi.firebasestorage.app',
    measurementId: 'G-51NRM9LN9Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgl51b5QI2jITjAtd7JJnU4LdGwwiS9Nw',
    appId: '1:429125840929:android:320fc861b313cee1037360',
    messagingSenderId: '429125840929',
    projectId: 'chikitsha-munshi',
    storageBucket: 'chikitsha-munshi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1UcqDw90h6JgTomXlFQ0qmkrWYKncP-0',
    appId: '1:429125840929:ios:5838539e6fbdf3f8037360',
    messagingSenderId: '429125840929',
    projectId: 'chikitsha-munshi',
    storageBucket: 'chikitsha-munshi.firebasestorage.app',
    iosBundleId: 'com.example.chikitshaMunshi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1UcqDw90h6JgTomXlFQ0qmkrWYKncP-0',
    appId: '1:429125840929:ios:5838539e6fbdf3f8037360',
    messagingSenderId: '429125840929',
    projectId: 'chikitsha-munshi',
    storageBucket: 'chikitsha-munshi.firebasestorage.app',
    iosBundleId: 'com.example.chikitshaMunshi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQ8OHaAlA7-xa4GB5efI9ppsppR2eVwh0',
    appId: '1:429125840929:web:ba61be891028294a037360',
    messagingSenderId: '429125840929',
    projectId: 'chikitsha-munshi',
    authDomain: 'chikitsha-munshi.firebaseapp.com',
    storageBucket: 'chikitsha-munshi.firebasestorage.app',
    measurementId: 'G-JJE6CJ3J5S',
  );
}
